[Junk]
addresses = """\
foo@bar.com
baz@spam.com
"""

re_addresses = '''
^spamonly@
triggerhappy
'''


[Awesome]
addresses = """
nifty@spiffy.com
"""

[RegexOnly]
re_addresses = '''
@example\.com$
'''

[Unused]
addresses = ""
re_addresses = ''
